### ISSUE TITLE
Remove Telemetry features

### ISSUE THREAD

**Issue by javahippie** [operaton/operaton#1]
**Is your feature request related to a problem? Please describe.**
The Camunda version we forked from still contained telemetry for reporting usage statistics to the vendor. We should remove this from the code base. 

**Describe the solution you'd like**
This has already happened within Camunda after our fork. We can follow their example and remove the "send to the vendor" parts, while keeping the Telemetry itself so that people who run the engine can access them by themselves and integrate it into their reporting

**Describe alternatives you've considered**
An alternative could be to disable the feature and remove the configuration for enabling it in the first step. The mere presence of this code could be a reason not to use the engine in some sensitive contexts, however.

**Comment by hauptmedia** [comment]
perhaps it would make sense to cherry pick & rewrite this commit? 
https://github.com/camunda/camunda-bpm-platform/commit/aa1f15bddbf56b1ed9c79851c7d664beb5994565
