### ISSUE TITLE
Set up Dependabot

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#15]
**Is your feature request related to a problem? Please describe.**
Keeping dependencies is a daily task for which Dependabot can used. 

**Describe the solution you'd like**
Set up Dependabot for GitHub projects as described for
- [Security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates)
- [Version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

Dependabot should then be able to raise automatic PRs.

**Comment by javahippie** [comment]
Hey Karsten, thanks for your suggestions (and all the other contributions, trying to take a look at them and merge them asap!)

We already set up dependabot checking, but not the automated PR feature. The plan was to check the issues it raised and create PRs by button-click, but I did not realize, that the issues listed by it on the "Security" tab might not be visible to people who are not in the maintainers group. 

I will try and enable it today 👍

**Comment by javahippie** [comment]
Enabled!
