### ISSUE TITLE
Rename Groups.CAMUNDA_ADMIN to Groups.OPERATON_ADMIN

### ISSUE THREAD

**Issue by hauptmedia** [operaton/operaton#196]
I’ve noticed that while class names throughout the code have been renamed, the constants haven’t been updated. Should these be renamed as well? I think it would make sense for consistency.

For example:

https://github.com/operaton/operaton/blob/9cc4fd7148be00920acc4a063afc5fdda91160d1/engine/src/main/java/org/operaton/bpm/engine/authorization/Groups.java#L26

**Comment by javahippie** [comment]
Hi @hauptmedia, you raised a good point, here. Some of the renamings were not 100% accurate.

What worries me a little more in the linked example (and what slipped by us in the initial renaming), that renaming the `camunda-admin` group to `operaton-admin` might break existing instances, as the group name is also saved in the database and then diverges 🤔

![grafik](https://github.com/user-attachments/assets/18177614-623b-44ce-9757-f4036385a983)

**Comment by hauptmedia** [comment]
Yes we need to migrate this in the database. Perhaps we can add an SQL script for the migration. 

It's a little bit more tricky with external auth configured (ldap, keycloak). We changed the keycloak plugin code that system groups can be defined using roles (vs "normal" groups being just keycloak groups). So we had to change the realm role name to make this work again.

**Comment by hauptmedia** [comment]
So do we have a consent for renaming this? This is a breaking change for the Keycloak plugin and it would be cool if we can decide on this before BETA-2 release

**Comment by javahippie** [comment]
We do have consent on renaming the variable names, yes!

**Comment by hauptmedia** [comment]
Already prepared the keycloak plugin for it, now waiting for merge and release of beta-2 => https://github.com/hauptmedia/operaton-keycloak/commit/e4d47b6d214d42439a780a47f395408607fcd920

**Comment by javahippie** [comment]
Fixed by #207
