### ISSUE TITLE
Handle SQL Migration Versions

### ISSUE THREAD

**Issue by hauptmedia** [operaton/operaton#203]
We need to decide how to manage SQL migration versioning.

Currently, the database version is set to 7.22.0 by Operaton. To ensure compatibility, we need to:

1.	Increase the database version to 7.23.0 after some release.
2.	Do this before merging any changes that rely on a modified data schema.

Reference:
See this commit for context: [396d635ce7](https://github.com/camunda/camunda-bpm-platform/commit/396d635ce7).

Note: This commit has not been backported yet

**Comment by kthoms** [comment]
@hauptmedia Do we need to set it actually to 7.23.0, or might be 8.0.0 a valid increment, although the schema does not change? IMO it is confusing to have a version number related to Camunda here.

**Comment by hauptmedia** [comment]
As long as we do not introduce database changes ourselfes we should stay with the C7 versioning scheme until 7.24. I already saw dabase changes incoming for 7.23.0. It's the only way - without doing bigger efforts - to seamlessly migrate all old c7 versions and the future 7.23/7.24 versions. Setting it to 8.0.0 now would mean we cannot differentiate if the user already applied the 7.23 or 7.24 database schema update

**Comment by hauptmedia** [comment]
Looking at the SQL migration files [here](https://github.com/operaton/operaton/blob/31d20645021551da572ed458a1fddddedf10da15/engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/postgres_engine_7.21_to_7.22.sql), I’ve noticed that there’s no check to verify if the column already exists before adding it.

This can cause issues for users upgrading from versions 7.23 or 7.24, as the migration will fail when attempting to add the column again with a version 8.0. To resolve this, we need to update the SQL scripts to ensure the column is added only if it doesn’t already exist.

This adjustment is straightforward for PostgreSQL, but we’ll also need to implement similar checks for other supported databases: MSSQL, MySQL, Oracle, DB2, and H2.

So my strategy is to delay this as much as possible and there is a good reason for us doing db changes that are Operaton only.

**Comment by hauptmedia** [comment]
This issue is resolved with 86a8cf6
