### ISSUE TITLE
(webapps) Update Screenshots on landing page

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#274]
**Describe the bug**
The Operaton landing page contains screenshots from Tasklist, Cockpit etc. which still show "Camunda".

**To Reproduce**
Start Operaton Tomcat distro.

**Expected behavior**
The screenshots should contain "Operaton" instead of "Camunda".

**Screenshots**
![Screenshot 320](https://github.com/user-attachments/assets/1961b6c6-e2d3-4424-a1ae-322582aa9323)

**Comment by hauptmedia** [comment]
It seems like there is also a Camunda logo still in the upper left corner next to "Operaton" which must be removed.

**Comment by AyalaFridman** [comment]
I would love to work on this, could you assign me this task?

**Comment by javahippie** [comment]
@AyalaFridman thanks a lot, assigned it to you!

**Comment by javahippie** [comment]
@AyalaFridman I unassigned you again. Feel free to reach out and pick up work in this issue, but I don't want it to appear blocked for others

**Comment by javahippie** [comment]
The logo was not found during the first replacement beacuse it is SVG: "M13,0 C20.1797017,0 26,5.82029825..."

Pinging @lambdaschmied2 could you create a replacement for that? After that I would take care of the new screenshots
