### ISSUE TITLE
Add <description> to all pom.xml files

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#293]
**Is your feature request related to a problem? Please describe.**
Most `pom.xml` files do not have a `<description>` tag.

This can be a problem e.g. when Maven Central is restrictive. For example, with strict checking JReleaser would fail:
```
[ERROR]     [mavenCentral] PomChecker detected errors in operaton-cmmn-model-1.0.0-beta-2.pom
[ERROR] <description> is not defined in POM. Will use value from parent: 
        Provides general dependencies and profiles for database testing
<url> is not defined in POM. Will use computed value from parent: 
```

**Describe the solution you'd like**
Add the description tag for each `pom.xml` file. Ideally with meaningful content, but could be also `${project.name}` by default.

**Comment by xProppi** [comment]
Hey, I have added the <description> tag to all pom.xml files. This is my Pull-Request. https://github.com/operaton/operaton/pull/298
