### ISSUE TITLE
Replace parent dependency from operaton-database-settings to operaton-parent

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#294]
**Describe the bug**
Many modules have declared `operaton-database-settings`, which itself has `operaton-parent` as parent.

Many of them do not need the database specific profiles of that POM, so they could have `operaton-parent` as parent.

**To Reproduce**
Search for `operaton-database-settings` in `pom.xml` files.

**Expected behavior**
Modules that safely can have `operaton-parent` should change their parent.

Please think carefully about unwanted side effects.

**Comment by shiftyseaotter** [comment]
I picked it up.
