### ISSUE TITLE
Create an Open Rewrite Script to support the migration process from Camunda to Operaton

### ISSUE THREAD

**Issue by javahippie** [operaton/operaton#3]
**Is your feature request related to a problem? Please describe.**
While we aim for the migration process to be as simple as possible (no changes for BPMN files, database..), the dependencies used in Camunda-projects need to be replaced an all package names adapted. This can be done with global search-and-replace tactics, but there is also tooling to automate these steps.

**Describe the solution you'd like**
With OpenRewrite it is possible to create recipes for automated code migrations. It would be nice if this functionality was available, so an existing Camunda project could be migrated to Operaton with a single Maven execution (or from the CLI). This enables users to test Operaton as a Camunda replacement with the lowest possible effort

**Comment by kthoms** [comment]
Where would these scripts be stored? They could be in a separate repository or also be part of the main repo. If the latter I would propose the following structure:
```
/sdk
  pom.xml (parent for tools to develop for Operaton)
  /rewrite
    pom.xml (parent for rewrite rules)
    /migration (module for Camunda->Operaton migration recipes)
    /testing (module for migration of test classes)
    /cleanup (module for code cleanup recipes)
```

**Comment by javahippie** [comment]
I would consider a separate repository for this. Currently, everything in the monorepo is (roughly) tied to the same release. The Rewrite script does not need to follow the "global" versioning schema, as this would imply a coupling between those

**Comment by javahippie** [comment]
I created a new repository [here](https://github.com/operaton/migrate-from-camunda-recipe), from the Moderne template repository as recommended [here](https://docs.openrewrite.org/authoring-recipes/recipe-development-environment)

**Comment by javahippie** [comment]
Closing this, progress is tracked in it's own repo now
