### ISSUE TITLE
Provide EditorConfig configuration

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#33]
**Is your feature request related to a problem? Please describe.**
Contributors should keep the style of existing code. If they use an IDE that supports [EditorConfig](https://editorconfig.org/) then having a configuration will be helpful for them.

**Describe the solution you'd like**
Provide a `.editorconfig` file in the project root.

The configuration should suite to the existing code as far as possible. This means, when auto-formatting code with a configured editor, the code should stay unchanged as far as possible.

**Comment by javahippie** [comment]
Reopened, because the .editorconfig interfered with `prettier` in the npm builds.

https://github.com/operaton/operaton/issues/63#issuecomment-2440545460

**Comment by javahippie** [comment]
As the `.editorconfig` does not contain any JS or HTML specific configurations, my suggestion is to try excluding it from `prettier` and check again

**Comment by hauptmedia** [comment]
btw there is already a file for this in this repo:

https://github.com/operaton/operaton/blob/main/CONTRIBUTING.md#contribution-checklist

which links to

https://github.com/operaton/operaton/tree/main/settings

https://github.com/camunda/camunda-bpm-platform/wiki/Coding-Style-Java

**Comment by kthoms** [comment]
Thanks. This makes it superfluous.
