### ISSUE TITLE
BPMN.io watermark is not visible in Cockpit

### ISSUE THREAD

**Issue by datakurre** [operaton/operaton#338]
From bpmn-js license:

>  The source code responsible for displaying the bpmn.io project watermark that
links back to https://bpmn.io as part of rendered diagrams MUST NOT be
removed or changed. When this software is being used in a website or application,
the watermark must stay fully visible and not visually overlapped by other elements.

Webapps should be fixed to show the watermark in bpmn-js and dmn-js.

**Comment by javahippie** [comment]
Excellent point, thank you!

**Comment by datakurre** [comment]
https://github.com/search?q=repo%3Aoperaton%2Foperaton%20bjs-powered-by&type=code

**Comment by datakurre** [comment]
Luckily they did not do anything fancy. Removing the .bjs-powered-by hide rules should fix it..

**Comment by datakurre** [comment]
That said, at least in process cockpit, the watermark overlaps zoom out, so some additional css fixes is required.

**Comment by javahippie** [comment]
Yes, just found it, too :) . Are you already working on it, or would you fine with me continuing?

**Comment by javahippie** [comment]
Suggestion: 

Before

![grafik](https://github.com/user-attachments/assets/d64a5590-1bff-47a2-b0bd-b1c7a8b1a46a)


After:

![grafik](https://github.com/user-attachments/assets/37c56614-163d-49d2-a9c0-98ad5ff2751e)
