### ISSUE TITLE
Set up automatic release process

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#37]
**Is your feature request related to a problem? Please describe.**
The project needs a release process that performs several tasks

- Building the release artifacts
- Deploy Jar artifacts to Maven Central
- Deploy release artifacts to GitHub
- Create and deploy change logs
- Tag sources
- Prepare sources for next development increment
- Update documentation
- Announcements
- Increment versions in sources
   - pom.xml
   - package.json

**Describe the solution you'd like**
The release process should be automated as far as possible. It should be triggered by a GitHub workflow with required parameters.

I would propose to leverage [JReleaser](https://jreleaser.org/guide/latest/index.html).
The setup for GitHub actions is described [here](https://jreleaser.org/guide/latest/continuous-integration/github-actions.html).

The setup will require to store some secrets, e.g. for Maven Central and PGP, and a token that allows JReleaser to make changes to the GitHub project.

**Describe alternatives you've considered**
The release actions can be scripted with Shell scripts and integrated in a GitHub workflow. However, many repeatable tasks are already provided by a solution like JReleaser.

**Additional context**
- none -

**Comment by javahippie** [comment]
I'm in favor of JReleaser, I never had a use case for it but I like the concept

**Comment by kthoms** [comment]
I could work on it, but would need assistance setting up the secrets.

**Comment by javahippie** [comment]
That's not an issue, I can assist with that. We could also work on this in a synchronuous session if you'd like

**Comment by hauptmedia** [comment]
We also need to decide how we should handle this => https://github.com/camunda/camunda-bpm-platform/commit/396d635ce7

This should be automated by the release pipeline

**Comment by kthoms** [comment]
@javahippie I would need to know what we would like to publish to Maven Central.
IMO the BOM `bom/operaton-only-bom/pom.xml` is a comprehensive list of modules to expect in Maven Central, the included BOMs recursively.
As distros "tomcat webapp" and "sqlscripts" come by default from the build, should be enough?

**Comment by kthoms** [comment]
package.json has to be updated, see https://github.com/operaton/operaton/pull/269/files

**Comment by kthoms** [comment]
For deployment to Maven Central there are some things to consider:

**Not all modules have to be deployed**
Deployment should be done only for a subset of modules. A large subset, though.
I'm considering currently this approach:
- By default (root POM) the maven-deploy-plugin is skipped by a property `deploy.skip`
- The property is set to `true` for modules that have to be deployed. Usually this is done on the reactor POMs, e.g. in `commons`
- Since deployment is deactivated by default and must not be inherited with activation, the following POMs have to be deployed explicity:
  - /pom.xml
  - /parent/pom.xml
  - /database/pom.xml

**Comment by kthoms** [comment]
I'll work differently now. I'll use the `sonatype-oss-release` profile. This contains already the modules to deploy. By default the deploy plugin will skip, but in this profile it is activated. Also it will execute the mandatory `maven-source-plugin` and `maven-javadoc-plugin`.

**Comment by kthoms** [comment]
The build with this profile fails on CI
```
Failed to execute goal on project operaton-xml-model: Could not resolve dependencies for project org.operaton.bpm.model:operaton-xml-model:jar:1.0.0-beta-2
dependency: org.operaton.bpm:operaton-bpm-archunit:jar:1.0.0-beta-2 (test)
```
Seems that archunit must be part of the profile's modules.

**Comment by kthoms** [comment]
Getting closer. The `release.yml` works locally with dry-run, the staging repo looks fine on first sight.
![Screenshot 324](https://github.com/user-attachments/assets/5e34f5f5-a519-4d94-a7d8-cff5c8ec56ce)
