### ISSUE TITLE
[build] Static code analysis

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#66]
**Is your feature request related to a problem? Please describe.**
It should be assured that the code quality matches certain criteria and pull requests do not violate that.

**Describe the solution you'd like**
Integrate static code analysis in the build process. Fail a PR build when requirements are not met.

I propose to use [Sonarqube](https://www.sonarsource.com/plans-and-pricing/sonarcloud/) for this. It is widely used and free for Open Source projects.

**Describe alternatives you've considered**
Not really, but surely there are alternatives.

**Comment by javahippie** [comment]
I'm looking into that one. If we host it on our infra, I'd like to see how we need to scale the server and what the security implication of pushing code from forked repositories there are. 

The SonarQube analysis can be heavy on the resources, so it would be a sensible configuration to only enable this analysis on Pull Requests

**Comment by kthoms** [comment]
I was more thinking of the SaaS version instead of managing a Sonarqube instance ourselves.
Look at the "cloud-based" pricing, still free for FOSS projects.

**Comment by javahippie** [comment]
https://sonarcloud.io/summary/new_code?id=operaton_operaton&pullRequest=74

The first build on the PR was successful. Unfortunately, there is a lot to do to make the analysis not fail (ignore code coverage, that's not properly configured, yet).

**Comment by kthoms** [comment]
Yes, let's start with a minimal setup and then add features. But great that you have been able to set it up.

Setting up code coverage would be a logical next step.

**Comment by javahippie** [comment]
Once this has been run on the main branch, for every PR only the delta should be analyzed. Maybe we can configure it to not fail on the main branch, but be more strict on PRs. Will check that
