### ISSUE TITLE
[build] Publish JUnit results in builds

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#67]
**Is your feature request related to a problem? Please describe.**
When a PR causes test failures it is not on first sight which test is failing. You need to dig into the console output to look that up.
Further, it is not visible how many tests have been performed.

**Describe the solution you'd like**
Add a step to the build workflow that publishes the JUnit test results.

This is how it could look like in the action using the [junit-report-action](https://github.com/marketplace/actions/junit-report-action):
![Uploading Bildschirmfoto 2024-10-28 um 13.48.24.png…]()

**Describe alternatives you've considered**
- Upload surefire reports as artifacts would create a zip and attach them to the build. We could consider this additionally.
- More GitHub actions exist that are doing similar things, e.g. [test-summary action](https://github.com/test-summary/action)

**Comment by kthoms** [comment]
Looks that it is working 🎉

![Bildschirmfoto 2024-10-28 um 22 04 04](https://github.com/user-attachments/assets/11626f8a-71d6-485c-bc61-6031d0368e42)

**Comment by javahippie** [comment]
That's a really useful addition, thanks!
