### ISSUE TITLE
Sonarqube Analysis step failing

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#80]
**Describe the bug**
With https://github.com/operaton/operaton/pull/74 Sonarqube analysis has been enabled.

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project operaton-root: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project operaton-root: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to
```

**To Reproduce**
[example log](https://github.com/operaton/operaton/actions/runs/11583527959/job/32248865826?pr=43) 

**Expected behavior**
Build is green

**Related**
#66

**Comment by javahippie** [comment]
I'm assuming that a PR from a forked Repo is not allowed to access the necessary secrets? "Project not found" can be an authorization issue with Sonarqube. Checking...

**Comment by javahippie** [comment]
The resources in that link won't help us as Sonarqube tells me that this project is too big for automated analysis. I'm afraid the only thing we can do is running the analysis on the main branch only and skipping it for merge requests, which is not ideal.

<img width="814" alt="grafik" src="https://github.com/user-attachments/assets/9a484dcf-8957-47e2-bdea-909d0e8066d1">

**Comment by javahippie** [comment]
Taking the liberty to close the issue, adressed by #81, #82
